version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Aruba-socket
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    # restart: always